import React,{useEffect} from "react";
import { Link } from "react-router-dom";
import Next from '../../components/arrow.svg'
import './Map.css'
import './Light.css'

const Text = () =>{

  useEffect(() => {
    function wrapLettersWithSpan(element){
        const text = element.innerText;
        const letters = text.split('');

        const wrappedText = letters.map(letter => {
            return `<span>${letter}</span>`;
        }).join('');

        element.innerHTML = wrappedText;
    }

    const animatedSpan = document.querySelector('.animated-text');

    wrapLettersWithSpan(animatedSpan);

    const letterSpans = animatedSpan.querySelectorAll('span');

    function animateLetters() {
        letterSpans.forEach((span, index) => {
          const randomDelay = Math.random() * 100 +1;
          span.style.animationDelay = `${index * randomDelay}ms`;
          span.classList.add('animate');
        });
      }
    
    animateLetters();
    
}, []);

  return(
    <>
    <div className="text-container">
          <p>
            <span className="animated-text" id="backlight">
              FADING AWAY
            </span>
          </p>
        </div>
    <Link to= "/Grid" id = 'button'>
    <img id='next-arrow'
              src={Next}
              alt='Next'
              />
    </Link>
    </>
  )
}


const Map = () => {

    return(
        <div className="introlight map">
    <div class="dotmap">
    
  <div class="maprow r19">
    <span class="dot r19d1 water"></span>
    <span class="dot r19d2 water"></span>
    <span class="dot r19d3 water"></span>
    <span class="dot r19d4 water"></span>
    <span class="dot r19d5 water"></span>
    <span class="dot r19d6 water"></span>
    <span class="dot r19d7 water"></span>
    <span class="dot r19d8 water"></span>
    <span class="dot r19d9 water"></span>
    <span class="dot r19d10 water"></span>
    <span class="dot r19d11 north-america"></span>
    <span class="dot r19d12 north-america"></span>
    <span class="dot r19d13 north-america"></span>
    <span class="dot r19d14 north-america"></span>
    <span class="dot r19d15 water"></span>
    <span class="dot r19d16 water"></span>
    <span class="dot r19d17 north-america"></span>
    <span class="dot r19d18 water"></span>
    <span class="dot r19d19 water"></span>
    <span class="dot r19d20 water"></span>
    <span class="dot r19d21 water"></span>
    <span class="dot r19d22 water"></span>
    <span class="dot r19d23 water"></span>
    <span class="dot r19d24 water"></span>
    <span class="dot r19d25 water"></span>
    <span class="dot r19d26 water"></span>
    <span class="dot r19d27 water"></span>
    <span class="dot r19d28 water"></span>
    <span class="dot r19d29 water"></span>
    <span class="dot r19d30 africa"></span>
    <span class="dot r19d31 africa"></span>
    <span class="dot r19d32 africa"></span>
    <span class="dot r19d33 africa"></span>
    <span class="dot r19d34 africa"></span>
    <span class="dot r19d35 africa"></span>
    <span class="dot r19d36 africa"></span>
    <span class="dot r19d37 africa"></span>
    <span class="dot r19d38 water"></span>
    <span class="dot r19d39 asia"></span>
    <span class="dot r19d40 asia"></span>
    <span class="dot r19d41 asia"></span>
    <span class="dot r19d42 asia"></span>
    <span class="dot r19d43 water"></span>
    <span class="dot r19d44 asia"></span>
    <span class="dot r19d45 asia"></span>
    <span class="dot r19d46 asia"></span>
    <span class="dot r19d47 asia"></span>
    <span class="dot r19d48 asia"></span>
    <span class="dot r19d49 asia"></span>
    <span class="dot r19d50 asia"></span>
    <span class="dot r19d51 asia"></span>
    <span class="dot r19d52 asia"></span>
    <span class="dot r19d53 asia"></span>
    <span class="dot r19d54 asia"></span>
    <span class="dot r19d55 asia"></span>
    <span class="dot r19d56 water"></span>
    <span class="dot r19d57 water"></span>
    <span class="dot r19d58 water"></span>
    <span class="dot r19d59 water"></span>
    <span class="dot r19d60 water"></span>
    <span class="dot r19d61 water"></span>
    <span class="dot r19d62 water"></span>
    <span class="dot r19d63 water"></span>
    <span class="dot r19d64 water"></span>
    <span class="dot r19d65 water"></span>
    <span class="dot r19d66 water"></span>
    <span class="dot r19d67 water"></span>
    <span class="dot r19d68 water"></span>
  </div>
  <div class="maprow r20">
    <span class="dot r20d1 water"></span>
    <span class="dot r20d2 north-america"></span>
    <span class="dot r20d3 north-america"></span>
    <span class="dot r20d4 water"></span>
    <span class="dot r20d5 water"></span>
    <span class="dot r20d6 water"></span>
    <span class="dot r20d7 water"></span>
    <span class="dot r20d8 water"></span>
    <span class="dot r20d9 water"></span>
    <span class="dot r20d10 water"></span>
    <span class="dot r20d11 water"></span>
    <span class="dot r20d12 water"></span>
    <span class="dot r20d13 north-america"></span>
    <span class="dot r20d14 north-america"></span>
    <span class="dot r20d15 water"></span>
    <span class="dot r20d16 north-america"></span>
    <span class="dot r20d17 north-america"></span>
    <span class="dot r20d18 water"></span>
    <span class="dot r20d19 water"></span>
    <span class="dot r20d20 water"></span>
    <span class="dot r20d21 water"></span>
    <span class="dot r20d22 water"></span>
    <span class="dot r20d23 water"></span>
    <span class="dot r20d24 water"></span>
    <span class="dot r20d25 water"></span>
    <span class="dot r20d26 water"></span>
    <span class="dot r20d27 water"></span>
    <span class="dot r20d28 water"></span>
    <span class="dot r20d29 africa"></span>
    <span class="dot r20d30 africa"></span>
    <span class="dot r20d31 africa"></span>
    <span class="dot r20d32 africa"></span>
    <span class="dot r20d33 africa"></span>
    <span class="dot r20d34 africa"></span>
    <span class="dot r20d35 africa"></span>
    <span class="dot r20d36 africa"></span>
    <span class="dot r20d37 africa"></span>
    <span class="dot r20d38 africa"></span>
    <span class="dot r20d39 water"></span>
    <span class="dot r20d40 asia"></span>
    <span class="dot r20d41 asia"></span>
    <span class="dot r20d42 asia"></span>
    <span class="dot r20d43 asia"></span>
    <span class="dot r20d44 water"></span>
    <span class="dot r20d45 water"></span>
    <span class="dot r20d46 asia"></span>
    <span class="dot r20d47 asia"></span>
    <span class="dot r20d48 asia"></span>
    <span class="dot r20d49 asia"></span>
    <span class="dot r20d50 asia"></span>
    <span class="dot r20d51 asia"></span>
    <span class="dot r20d52 asia"></span>
    <span class="dot r20d53 asia"></span>
    <span class="dot r20d54 asia"></span>
    <span class="dot r20d55 asia"></span>
    <span class="dot r20d56 water"></span>
    <span class="dot r20d57 water"></span>
    <span class="dot r20d58 water"></span>
    <span class="dot r20d59 water"></span>
    <span class="dot r20d60 water"></span>
    <span class="dot r20d61 water"></span>
    <span class="dot r20d62 water"></span>
    <span class="dot r20d63 water"></span>
    <span class="dot r20d64 water"></span>
    <span class="dot r20d65 water"></span>
    <span class="dot r20d66 water"></span>
    <span class="dot r20d67 water"></span>
    <span class="dot r20d68 water"></span>
  </div>
  <div class="maprow r21">
    <span class="dot r21d1 water"></span>
    <span class="dot r21d2 water"></span>
    <span class="dot r21d3 water"></span>
    <span class="dot r21d4 water"></span>
    <span class="dot r21d5 water"></span>
    <span class="dot r21d6 water"></span>
    <span class="dot r21d7 water"></span>
    <span class="dot r21d8 water"></span>
    <span class="dot r21d9 water"></span>
    <span class="dot r21d10 water"></span>
    <span class="dot r21d11 water"></span>
    <span class="dot r21d12 water"></span>
    <span class="dot r21d13 north-america"></span>
    <span class="dot r21d14 north-america"></span>
    <span class="dot r21d15 north-america"></span>
    <span class="dot r21d16 north-america"></span>
    <span class="dot r21d17 water"></span>
    <span class="dot r21d18 north-america"></span>
    <span class="dot r21d19 north-america"></span>
    <span class="dot r21d20 water"></span>
    <span class="dot r21d21 water"></span>
    <span class="dot r21d22 water"></span>
    <span class="dot r21d23 water"></span>
    <span class="dot r21d24 water"></span>
    <span class="dot r21d25 water"></span>
    <span class="dot r21d26 water"></span>
    <span class="dot r21d27 water"></span>
    <span class="dot r21d28 water"></span>
    <span class="dot r21d29 africa"></span>
    <span class="dot r21d30 africa"></span>
    <span class="dot r21d31 africa"></span>
    <span class="dot r21d32 africa"></span>
    <span class="dot r21d33 africa"></span>
    <span class="dot r21d34 africa"></span>
    <span class="dot r21d35 africa"></span>
    <span class="dot r21d36 africa"></span>
    <span class="dot r21d37 africa"></span>
    <span class="dot r21d38 africa"></span>
    <span class="dot r21d39 africa"></span>
    <span class="dot r21d40 water"></span>
    <span class="dot r21d41 asia"></span>
    <span class="dot r21d42 asia"></span>
    <span class="dot r21d43 asia"></span>
    <span class="dot r21d44 water"></span>
    <span class="dot r21d45 water"></span>
    <span class="dot r21d46 asia"></span>
    <span class="dot r21d47 asia"></span>
    <span class="dot r21d48 asia"></span>
    <span class="dot r21d49 water"></span>
    <span class="dot r21d50 asia"></span>
    <span class="dot r21d51 asia"></span>
    <span class="dot r21d52 asia"></span>
    <span class="dot r21d53 water"></span>
    <span class="dot r21d54 water"></span>
    <span class="dot r21d55 asia"></span>
    <span class="dot r21d56 water"></span>
    <span class="dot r21d57 water"></span>
    <span class="dot r21d58 water"></span>
    <span class="dot r21d59 water"></span>
    <span class="dot r21d60 water"></span>
    <span class="dot r21d61 water"></span>
    <span class="dot r21d62 water"></span>
    <span class="dot r21d63 water"></span>
    <span class="dot r21d64 water"></span>
    <span class="dot r21d65 water"></span>
    <span class="dot r21d66 water"></span>
    <span class="dot r21d67 water"></span>
    <span class="dot r21d68 water"></span>
  </div>
  <div class="maprow r22">
    <span class="dot r22d1 water"></span>
    <span class="dot r22d2 water"></span>
    <span class="dot r22d3 water"></span>
    <span class="dot r22d4 water"></span>
    <span class="dot r22d5 water"></span>
    <span class="dot r22d6 water"></span>
    <span class="dot r22d7 water"></span>
    <span class="dot r22d8 water"></span>
    <span class="dot r22d9 water"></span>
    <span class="dot r22d10 water"></span>
    <span class="dot r22d11 water"></span>
    <span class="dot r22d12 water"></span>
    <span class="dot r22d13 water"></span>
    <span class="dot r22d14 water"></span>
    <span class="dot r22d15 water"></span>
    <span class="dot r22d16 north-america"></span>
    <span class="dot r22d17 north-america"></span>
    <span class="dot r22d18 water"></span>
    <span class="dot r22d19 water"></span>
    <span class="dot r22d20 south-america"></span>
    <span class="dot r22d21 south-america"></span>
    <span class="dot r22d22 water"></span>
    <span class="dot r22d23 water"></span>
    <span class="dot r22d24 water"></span>
    <span class="dot r22d25 water"></span>
    <span class="dot r22d26 water"></span>
    <span class="dot r22d27 water"></span>
    <span class="dot r22d28 water"></span>
    <span class="dot r22d29 africa"></span>
    <span class="dot r22d30 africa"></span>
    <span class="dot r22d31 africa"></span>
    <span class="dot r22d32 africa"></span>
    <span class="dot r22d33 africa"></span>
    <span class="dot r22d34 africa"></span>
    <span class="dot r22d35 africa"></span>
    <span class="dot r22d36 africa"></span>
    <span class="dot r22d37 africa"></span>
    <span class="dot r22d38 africa"></span>
    <span class="dot r22d39 africa"></span>
    <span class="dot r22d40 africa"></span>
    <span class="dot r22d41 water"></span>
    <span class="dot r22d42 water"></span>
    <span class="dot r22d43 water"></span>
    <span class="dot r22d44 water"></span>
    <span class="dot r22d45 water"></span>
    <span class="dot r22d46 water"></span>
    <span class="dot r22d47 asia"></span>
    <span class="dot r22d48 water"></span>
    <span class="dot r22d49 water"></span>
    <span class="dot r22d50 water"></span>
    <span class="dot r22d51 asia"></span>
    <span class="dot r22d52 asia"></span>
    <span class="dot r22d53 asia"></span>
    <span class="dot r22d54 water"></span>
    <span class="dot r22d55 asia"></span>
    <span class="dot r22d56 asia"></span>
    <span class="dot r22d57 water"></span>
    <span class="dot r22d58 water"></span>
    <span class="dot r22d59 water"></span>
    <span class="dot r22d60 water"></span>
    <span class="dot r22d61 water"></span>
    <span class="dot r22d62 water"></span>
    <span class="dot r22d63 water"></span>
    <span class="dot r22d64 water"></span>
    <span class="dot r22d65 water"></span>
    <span class="dot r22d66 water"></span>
    <span class="dot r22d67 water"></span>
    <span class="dot r22d68 water"></span>
  </div>
  <div class="maprow r23">
    <span class="dot r23d1 water"></span>
    <span class="dot r23d2 water"></span>
    <span class="dot r23d3 water"></span>
    <span class="dot r23d4 water"></span>
    <span class="dot r23d5 water"></span>
    <span class="dot r23d6 water"></span>
    <span class="dot r23d7 water"></span>
    <span class="dot r23d8 water"></span>
    <span class="dot r23d9 water"></span>
    <span class="dot r23d10 water"></span>
    <span class="dot r23d11 water"></span>
    <span class="dot r23d12 water"></span>
    <span class="dot r23d13 water"></span>
    <span class="dot r23d14 water"></span>
    <span class="dot r23d15 water"></span>
    <span class="dot r23d16 water"></span>
    <span class="dot r23d17 north-america"></span>
    <span class="dot r23d18 south-america"></span>
    <span class="dot r23d19 south-america"></span>
    <span class="dot r23d20 south-america"></span>
    <span class="dot r23d21 south-america"></span>
    <span class="dot r23d22 south-america"></span>
    <span class="dot r23d23 water"></span>
    <span class="dot r23d24 water"></span>
    <span class="dot r23d25 water"></span>
    <span class="dot r23d26 water"></span>
    <span class="dot r23d27 water"></span>
    <span class="dot r23d28 water"></span>
    <span class="dot r23d29 water"></span>
    <span class="dot r23d30 africa"></span>
    <span class="dot r23d31 africa"></span>
    <span class="dot r23d32 africa"></span>
    <span class="dot r23d33 africa"></span>
    <span class="dot r23d34 africa"></span>
    <span class="dot r23d35 africa"></span>
    <span class="dot r23d36 africa"></span>
    <span class="dot r23d37 africa"></span>
    <span class="dot r23d38 africa"></span>
    <span class="dot r23d39 africa"></span>
    <span class="dot r23d40 africa"></span>
    <span class="dot r23d41 africa"></span>
    <span class="dot r23d42 africa"></span>
    <span class="dot r23d43 water"></span>
    <span class="dot r23d44 water"></span>
    <span class="dot r23d45 water"></span>
    <span class="dot r23d46 water"></span>
    <span class="dot r23d47 asia"></span>
    <span class="dot r23d48 water"></span>
    <span class="dot r23d49 water"></span>
    <span class="dot r23d50 water"></span>
    <span class="dot r23d51 water"></span>
    <span class="dot r23d52 asia"></span>
    <span class="dot r23d53 water"></span>
    <span class="dot r23d54 water"></span>
    <span class="dot r23d55 asia"></span>
    <span class="dot r23d56 asia"></span>
    <span class="dot r23d57 water"></span>
    <span class="dot r23d58 water"></span>
    <span class="dot r23d59 water"></span>
    <span class="dot r23d60 water"></span>
    <span class="dot r23d61 water"></span>
    <span class="dot r23d62 water"></span>
    <span class="dot r23d63 water"></span>
    <span class="dot r23d64 water"></span>
    <span class="dot r23d65 water"></span>
    <span class="dot r23d66 water"></span>
    <span class="dot r23d67 water"></span>
    <span class="dot r23d68 water"></span>
  </div>
  <div class="maprow r24">
    <span class="dot r24d1 water"></span>
    <span class="dot r24d2 water"></span>
    <span class="dot r24d3 water"></span>
    <span class="dot r24d4 water"></span>
    <span class="dot r24d5 water"></span>
    <span class="dot r24d6 water"></span>
    <span class="dot r24d7 water"></span>
    <span class="dot r24d8 water"></span>
    <span class="dot r24d9 water"></span>
    <span class="dot r24d10 water"></span>
    <span class="dot r24d11 water"></span>
    <span class="dot r24d12 water"></span>
    <span class="dot r24d13 water"></span>
    <span class="dot r24d14 water"></span>
    <span class="dot r24d15 water"></span>
    <span class="dot r24d16 water"></span>
    <span class="dot r24d17 south-america"></span>
    <span class="dot r24d18 south-america"></span>
    <span class="dot r24d19 south-america"></span>
    <span class="dot r24d20 south-america"></span>
    <span class="dot r24d21 south-america"></span>
    <span class="dot r24d22 south-america"></span>
    <span class="dot r24d23 south-america"></span>
    <span class="dot r24d24 water"></span>
    <span class="dot r24d25 water"></span>
    <span class="dot r24d26 water"></span>
    <span class="dot r24d27 water"></span>
    <span class="dot r24d28 water"></span>
    <span class="dot r24d29 water"></span>
    <span class="dot r24d30 water"></span>
    <span class="dot r24d31 africa"></span>
    <span class="dot r24d32 africa"></span>
    <span class="dot r24d33 africa"></span>
    <span class="dot r24d34 africa"></span>
    <span class="dot r24d35 africa"></span>
    <span class="dot r24d36 africa"></span>
    <span class="dot r24d37 africa"></span>
    <span class="dot r24d38 africa"></span>
    <span class="dot r24d39 africa"></span>
    <span class="dot r24d40 africa"></span>
    <span class="dot r24d41 africa"></span>
    <span class="dot r24d42 water"></span>
    <span class="dot r24d43 water"></span>
    <span class="dot r24d44 water"></span>
    <span class="dot r24d45 water"></span>
    <span class="dot r24d46 water"></span>
    <span class="dot r24d47 water"></span>
    <span class="dot r24d48 asia"></span>
    <span class="dot r24d49 water"></span>
    <span class="dot r24d50 water"></span>
    <span class="dot r24d51 asia"></span>
    <span class="dot r24d52 water"></span>
    <span class="dot r24d53 water"></span>
    <span class="dot r24d54 asia"></span>
    <span class="dot r24d55 water"></span>
    <span class="dot r24d56 asia"></span>
    <span class="dot r24d57 water"></span>
    <span class="dot r24d58 water"></span>
    <span class="dot r24d59 water"></span>
    <span class="dot r24d60 water"></span>
    <span class="dot r24d61 water"></span>
    <span class="dot r24d62 water"></span>
    <span class="dot r24d63 water"></span>
    <span class="dot r24d64 water"></span>
    <span class="dot r24d65 water"></span>
    <span class="dot r24d66 water"></span>
    <span class="dot r24d67 water"></span>
    <span class="dot r24d68 water"></span>
  </div>
  <div class="maprow r25">
    <span class="dot r25d1 water"></span>
    <span class="dot r25d2 water"></span>
    <span class="dot r25d3 water"></span>
    <span class="dot r25d4 water"></span>
    <span class="dot r25d5 water"></span>
    <span class="dot r25d6 water"></span>
    <span class="dot r25d7 water"></span>
    <span class="dot r25d8 water"></span>
    <span class="dot r25d9 water"></span>
    <span class="dot r25d10 water"></span>
    <span class="dot r25d11 water"></span>
    <span class="dot r25d12 water"></span>
    <span class="dot r25d13 water"></span>
    <span class="dot r25d14 water"></span>
    <span class="dot r25d15 water"></span>
    <span class="dot r25d16 water"></span>
    <span class="dot r25d17 south-america"></span>
    <span class="dot r25d18 south-america"></span>
    <span class="dot r25d19 south-america"></span>
    <span class="dot r25d20 south-america"></span>
    <span class="dot r25d21 south-america"></span>
    <span class="dot r25d22 south-america"></span>
    <span class="dot r25d23 south-america"></span>
    <span class="dot r25d24 south-america"></span>
    <span class="dot r25d25 water"></span>
    <span class="dot r25d26 water"></span>
    <span class="dot r25d27 water"></span>
    <span class="dot r25d28 water"></span>
    <span class="dot r25d29 water"></span>
    <span class="dot r25d30 water"></span>
    <span class="dot r25d31 water"></span>
    <span class="dot r25d32 water"></span>
    <span class="dot r25d33 water"></span>
    <span class="dot r25d34 africa"></span>
    <span class="dot r25d35 africa"></span>
    <span class="dot r25d36 africa"></span>
    <span class="dot r25d37 africa"></span>
    <span class="dot r25d38 africa"></span>
    <span class="dot r25d39 africa"></span>
    <span class="dot r25d40 africa"></span>
    <span class="dot r25d41 water"></span>
    <span class="dot r25d42 water"></span>
    <span class="dot r25d43 water"></span>
    <span class="dot r25d44 water"></span>
    <span class="dot r25d45 water"></span>
    <span class="dot r25d46 water"></span>
    <span class="dot r25d47 water"></span>
    <span class="dot r25d48 water"></span>
    <span class="dot r25d49 water"></span>
    <span class="dot r25d50 water"></span>
    <span class="dot r25d51 asia"></span>
    <span class="dot r25d52 asia"></span>
    <span class="dot r25d53 asia"></span>
    <span class="dot r25d54 asia"></span>
    <span class="dot r25d55 asia"></span>
    <span class="dot r25d56 asia"></span>
    <span class="dot r25d57 asia"></span>
    <span class="dot r25d58 asia"></span>
    <span class="dot r25d59 water"></span>
    <span class="dot r25d60 water"></span>
    <span class="dot r25d61 water"></span>
    <span class="dot r25d62 water"></span>
    <span class="dot r25d63 water"></span>
    <span class="dot r25d64 water"></span>
    <span class="dot r25d65 water"></span>
    <span class="dot r25d66 water"></span>
    <span class="dot r25d67 water"></span>
    <span class="dot r25d68 water"></span>
  </div>
  <div class="maprow r26">
    <span class="dot r26d1 water"></span>
    <span class="dot r26d2 water"></span>
    <span class="dot r26d3 water"></span>
    <span class="dot r26d4 water"></span>
    <span class="dot r26d5 water"></span>
    <span class="dot r26d6 water"></span>
    <span class="dot r26d7 water"></span>
    <span class="dot r26d8 water"></span>
    <span class="dot r26d9 water"></span>
    <span class="dot r26d10 water"></span>
    <span class="dot r26d11 water"></span>
    <span class="dot r26d12 water"></span>
    <span class="dot r26d13 water"></span>
    <span class="dot r26d14 water"></span>
    <span class="dot r26d15 water"></span>
    <span class="dot r26d16 water"></span>
    <span class="dot r26d17 south-america"></span>
    <span class="dot r26d18 south-america"></span>
    <span class="dot r26d19 south-america"></span>
    <span class="dot r26d20 south-america"></span>
    <span class="dot r26d21 south-america"></span>
    <span class="dot r26d22 south-america"></span>
    <span class="dot r26d23 south-america"></span>
    <span class="dot r26d24 south-america"></span>
    <span class="dot r26d25 south-america"></span>
    <span class="dot r26d26 south-america"></span>
    <span class="dot r26d27 water"></span>
    <span class="dot r26d28 water"></span>
    <span class="dot r26d29 water"></span>
    <span class="dot r26d30 water"></span>
    <span class="dot r26d31 water"></span>
    <span class="dot r26d32 water"></span>
    <span class="dot r26d33 water"></span>
    <span class="dot r26d34 water"></span>
    <span class="dot r26d35 africa"></span>
    <span class="dot r26d36 africa"></span>
    <span class="dot r26d37 africa"></span>
    <span class="dot r26d38 africa"></span>
    <span class="dot r26d39 africa"></span>
    <span class="dot r26d40 africa"></span>
    <span class="dot r26d41 water"></span>
    <span class="dot r26d42 water"></span>
    <span class="dot r26d43 water"></span>
    <span class="dot r26d44 water"></span>
    <span class="dot r26d45 water"></span>
    <span class="dot r26d46 water"></span>
    <span class="dot r26d47 water"></span>
    <span class="dot r26d48 water"></span>
    <span class="dot r26d49 water"></span>
    <span class="dot r26d50 water"></span>
    <span class="dot r26d51 water"></span>
    <span class="dot r26d52 asia"></span>
    <span class="dot r26d53 asia"></span>
    <span class="dot r26d54 water"></span>
    <span class="dot r26d55 asia"></span>
    <span class="dot r26d56 water"></span>
    <span class="dot r26d57 water"></span>
    <span class="dot r26d58 australia"></span>
    <span class="dot r26d59 australia"></span>
    <span class="dot r26d60 australia"></span>
    <span class="dot r26d61 australia"></span>
    <span class="dot r26d62 australia"></span>
    <span class="dot r26d63 water"></span>
    <span class="dot r26d64 water"></span>
    <span class="dot r26d65 water"></span>
    <span class="dot r26d66 water"></span>
    <span class="dot r26d67 water"></span>
    <span class="dot r26d68 water"></span>
  </div>
  <div class="maprow r27">
    <span class="dot r27d1 water"></span>
    <span class="dot r27d2 water"></span>
    <span class="dot r27d3 water"></span>
    <span class="dot r27d4 water"></span>
    <span class="dot r27d5 water"></span>
    <span class="dot r27d6 water"></span>
    <span class="dot r27d7 water"></span>
    <span class="dot r27d8 water"></span>
    <span class="dot r27d9 water"></span>
    <span class="dot r27d10 water"></span>
    <span class="dot r27d11 water"></span>
    <span class="dot r27d12 water"></span>
    <span class="dot r27d13 water"></span>
    <span class="dot r27d14 water"></span>
    <span class="dot r27d15 water"></span>
    <span class="dot r27d16 water"></span>
    <span class="dot r27d17 water"></span>
    <span class="dot r27d18 south-america"></span>
    <span class="dot r27d19 south-america"></span>
    <span class="dot r27d20 south-america"></span>
    <span class="dot r27d21 south-america"></span>
    <span class="dot r27d22 south-america"></span>
    <span class="dot r27d23 south-america"></span>
    <span class="dot r27d24 south-america"></span>
    <span class="dot r27d25 south-america"></span>
    <span class="dot r27d26 south-america"></span>
    <span class="dot r27d27 water"></span>
    <span class="dot r27d28 water"></span>
    <span class="dot r27d29 water"></span>
    <span class="dot r27d30 water"></span>
    <span class="dot r27d31 water"></span>
    <span class="dot r27d32 water"></span>
    <span class="dot r27d33 water"></span>
    <span class="dot r27d34 water"></span>
    <span class="dot r27d35 africa"></span>
    <span class="dot r27d36 africa"></span>
    <span class="dot r27d37 africa"></span>
    <span class="dot r27d38 africa"></span>
    <span class="dot r27d39 africa"></span>
    <span class="dot r27d40 africa"></span>
    <span class="dot r27d41 water"></span>
    <span class="dot r27d42 water"></span>
    <span class="dot r27d43 water"></span>
    <span class="dot r27d44 water"></span>
    <span class="dot r27d45 water"></span>
    <span class="dot r27d46 water"></span>
    <span class="dot r27d47 water"></span>
    <span class="dot r27d48 water"></span>
    <span class="dot r27d49 water"></span>
    <span class="dot r27d50 water"></span>
    <span class="dot r27d51 water"></span>
    <span class="dot r27d52 water"></span>
    <span class="dot r27d53 water"></span>
    <span class="dot r27d54 asia"></span>
    <span class="dot r27d55 water"></span>
    <span class="dot r27d56 water"></span>
    <span class="dot r27d57 australia"></span>
    <span class="dot r27d58 water"></span>
    <span class="dot r27d59 australia"></span>
    <span class="dot r27d60 australia"></span>
    <span class="dot r27d61 water"></span>
    <span class="dot r27d62 water"></span>
    <span class="dot r27d63 australia"></span>
    <span class="dot r27d64 water"></span>
    <span class="dot r27d65 water"></span>
    <span class="dot r27d66 water"></span>
    <span class="dot r27d67 water"></span>
    <span class="dot r27d68 water"></span>
  </div>
  <div class="maprow r28">
    <span class="dot r28d1 water"></span>
    <span class="dot r28d2 water"></span>
    <span class="dot r28d3 water"></span>
    <span class="dot r28d4 water"></span>
    <span class="dot r28d5 water"></span>
    <span class="dot r28d6 water"></span>
    <span class="dot r28d7 water"></span>
    <span class="dot r28d8 water"></span>
    <span class="dot r28d9 water"></span>
    <span class="dot r28d10 water"></span>
    <span class="dot r28d11 water"></span>
    <span class="dot r28d12 water"></span>
    <span class="dot r28d13 water"></span>
    <span class="dot r28d14 water"></span>
    <span class="dot r28d15 water"></span>
    <span class="dot r28d16 water"></span>
    <span class="dot r28d17 water"></span>
    <span class="dot r28d18 south-america"></span>
    <span class="dot r28d19 south-america"></span>
    <span class="dot r28d20 south-america"></span>
    <span class="dot r28d21 south-america"></span>
    <span class="dot r28d22 south-america"></span>
    <span class="dot r28d23 south-america"></span>
    <span class="dot r28d24 south-america"></span>
    <span class="dot r28d25 south-america"></span>
    <span class="dot r28d26 water"></span>
    <span class="dot r28d27 water"></span>
    <span class="dot r28d28 water"></span>
    <span class="dot r28d29 water"></span>
    <span class="dot r28d30 water"></span>
    <span class="dot r28d31 water"></span>
    <span class="dot r28d32 water"></span>
    <span class="dot r28d33 water"></span>
    <span class="dot r28d34 water"></span>
    <span class="dot r28d35 africa"></span>
    <span class="dot r28d36 africa"></span>
    <span class="dot r28d37 africa"></span>
    <span class="dot r28d38 africa"></span>
    <span class="dot r28d39 africa"></span>
    <span class="dot r28d40 africa"></span>
    <span class="dot r28d41 africa"></span>
    <span class="dot r28d42 water"></span>
    <span class="dot r28d43 water"></span>
    <span class="dot r28d44 water"></span>
    <span class="dot r28d45 water"></span>
    <span class="dot r28d46 water"></span>
    <span class="dot r28d47 water"></span>
    <span class="dot r28d48 water"></span>
    <span class="dot r28d49 water"></span>
    <span class="dot r28d50 water"></span>
    <span class="dot r28d51 water"></span>
    <span class="dot r28d52 water"></span>
    <span class="dot r28d53 water"></span>
    <span class="dot r28d54 water"></span>
    <span class="dot r28d55 water"></span>
    <span class="dot r28d56 australia"></span>
    <span class="dot r28d57 australia"></span>
    <span class="dot r28d58 australia"></span>
    <span class="dot r28d59 australia"></span>
    <span class="dot r28d60 water"></span>
    <span class="dot r28d61 water"></span>
    <span class="dot r28d62 water"></span>
    <span class="dot r28d63 water"></span>
    <span class="dot r28d64 water"></span>
    <span class="dot r28d65 water"></span>
    <span class="dot r28d66 water"></span>
    <span class="dot r28d67 water"></span>
    <span class="dot r28d68 water"></span>
  </div>
  <div class="maprow r29">
    <span class="dot r29d1 water"></span>
    <span class="dot r29d2 water"></span>
    <span class="dot r29d3 water"></span>
    <span class="dot r29d4 water"></span>
    <span class="dot r29d5 water"></span>
    <span class="dot r29d6 water"></span>
    <span class="dot r29d7 water"></span>
    <span class="dot r29d8 water"></span>
    <span class="dot r29d9 water"></span>
    <span class="dot r29d10 water"></span>
    <span class="dot r29d11 water"></span>
    <span class="dot r29d12 water"></span>
    <span class="dot r29d13 water"></span>
    <span class="dot r29d14 water"></span>
    <span class="dot r29d15 water"></span>
    <span class="dot r29d16 water"></span>
    <span class="dot r29d17 water"></span>
    <span class="dot r29d18 water"></span>
    <span class="dot r29d19 south-america"></span>
    <span class="dot r29d20 south-america"></span>
    <span class="dot r29d21 south-america"></span>
    <span class="dot r29d22 south-america"></span>
    <span class="dot r29d23 south-america"></span>
    <span class="dot r29d24 south-america"></span>
    <span class="dot r29d25 south-america"></span>
    <span class="dot r29d26 water"></span>
    <span class="dot r29d27 water"></span>
    <span class="dot r29d28 water"></span>
    <span class="dot r29d29 water"></span>
    <span class="dot r29d30 water"></span>
    <span class="dot r29d31 water"></span>
    <span class="dot r29d32 water"></span>
    <span class="dot r29d33 water"></span>
    <span class="dot r29d34 water"></span>
    <span class="dot r29d35 africa flicker"></span>
    <span class="dot r29d36 africa flicker"></span>
    <span class="dot r29d37 africa flicker"></span>
    <span class="dot r29d38 africa flicker"></span>
    <span class="dot r29d39 africa flicker"></span>
    <span class="dot r29d40 water"></span>
    <span class="dot r29d41 africa"></span>
    <span class="dot r29d42 water"></span>
    <span class="dot r29d43 water"></span>
    <span class="dot r29d44 water"></span>
    <span class="dot r29d45 water"></span>
    <span class="dot r29d46 water"></span>
    <span class="dot r29d47 water"></span>
    <span class="dot r29d48 water"></span>
    <span class="dot r29d49 water"></span>
    <span class="dot r29d50 water"></span>
    <span class="dot r29d51 water"></span>
    <span class="dot r29d52 water"></span>
    <span class="dot r29d53 water"></span>
    <span class="dot r29d54 water"></span>
    <span class="dot r29d55 australia"></span>
    <span class="dot r29d56 australia"></span>
    <span class="dot r29d57 australia"></span>
    <span class="dot r29d58 australia"></span>
    <span class="dot r29d59 australia"></span>
    <span class="dot r29d60 australia"></span>
    <span class="dot r29d61 water"></span>
    <span class="dot r29d62 water"></span>
    <span class="dot r29d63 water"></span>
    <span class="dot r29d64 water"></span>
    <span class="dot r29d65 water"></span>
    <span class="dot r29d66 water"></span>
    <span class="dot r29d67 water"></span>
    <span class="dot r29d68 water"></span>
  </div>
  <div class="maprow r30">
    <span class="dot r30d1 water"></span>
    <span class="dot r30d2 water"></span>
    <span class="dot r30d3 water"></span>
    <span class="dot r30d4 water"></span>
    <span class="dot r30d5 water"></span>
    <span class="dot r30d6 water"></span>
    <span class="dot r30d7 water"></span>
    <span class="dot r30d8 water"></span>
    <span class="dot r30d9 water"></span>
    <span class="dot r30d10 water"></span>
    <span class="dot r30d11 water"></span>
    <span class="dot r30d12 water"></span>
    <span class="dot r30d13 water"></span>
    <span class="dot r30d14 water"></span>
    <span class="dot r30d15 water"></span>
    <span class="dot r30d16 water"></span>
    <span class="dot r30d17 water"></span>
    <span class="dot r30d18 water"></span>
    <span class="dot r30d19 south-america"></span>
    <span class="dot r30d20 south-america"></span>
    <span class="dot r30d21 south-america"></span>
    <span class="dot r30d22 south-america"></span>
    <span class="dot r30d23 south-america"></span>
    <span class="dot r30d24 south-america"></span>
    <span class="dot r30d25 water"></span>
    <span class="dot r30d26 water"></span>
    <span class="dot r30d27 water"></span>
    <span class="dot r30d28 water"></span>
    <span class="dot r30d29 water"></span>
    <span class="dot r30d30 water"></span>
    <span class="dot r30d31 water"></span>
    <span class="dot r30d32 water"></span>
    <span class="dot r30d33 water"></span>
    <span class="dot r30d34 water"></span>
    <span class="dot r30d35 africa flicker"></span>
    <span class="dot r30d36 africa flicker"></span>
    <span class="dot r30d37 africa flicker"></span>
    <span class="dot r30d38 africa flicker"></span>
    <span class="dot r30d39 africa flicker"></span>
    <span class="dot r30d40 water"></span>
    <span class="dot r30d41 africa"></span>
    <span class="dot r30d42 water"></span>
    <span class="dot r30d43 water"></span>
    <span class="dot r30d44 water"></span>
    <span class="dot r30d45 water"></span>
    <span class="dot r30d46 water"></span>
    <span class="dot r30d47 water"></span>
    <span class="dot r30d48 water"></span>
    <span class="dot r30d49 water"></span>
    <span class="dot r30d50 water"></span>
    <span class="dot r30d51 water"></span>
    <span class="dot r30d52 water"></span>
    <span class="dot r30d53 water"></span>
    <span class="dot r30d54 australia"></span>
    <span class="dot r30d55 australia"></span>
    <span class="dot r30d56 australia"></span>
    <span class="dot r30d57 australia"></span>
    <span class="dot r30d58 australia"></span>
    <span class="dot r30d59 australia"></span>
    <span class="dot r30d60 australia"></span>
    <span class="dot r30d61 australia"></span>
    <span class="dot r30d62 water"></span>
    <span class="dot r30d63 water"></span>
    <span class="dot r30d64 water"></span>
    <span class="dot r30d65 water"></span>
    <span class="dot r30d66 water"></span>
    <span class="dot r30d67 water"></span>
    <span class="dot r30d68 water"></span>
  </div>
  <div class="maprow r31">
    <span class="dot r31d1 water"></span>
    <span class="dot r31d2 water"></span>
    <span class="dot r31d3 water"></span>
    <span class="dot r31d4 water"></span>
    <span class="dot r31d5 water"></span>
    <span class="dot r31d6 water"></span>
    <span class="dot r31d7 water"></span>
    <span class="dot r31d8 water"></span>
    <span class="dot r31d9 water"></span>
    <span class="dot r31d10 water"></span>
    <span class="dot r31d11 water"></span>
    <span class="dot r31d12 water"></span>
    <span class="dot r31d13 water"></span>
    <span class="dot r31d14 water"></span>
    <span class="dot r31d15 water"></span>
    <span class="dot r31d16 water"></span>
    <span class="dot r31d17 water"></span>
    <span class="dot r31d18 water"></span>
    <span class="dot r31d19 south-america"></span>
    <span class="dot r31d20 south-america"></span>
    <span class="dot r31d21 south-america"></span>
    <span class="dot r31d22 south-america"></span>
    <span class="dot r31d23 south-america"></span>
    <span class="dot r31d24 water"></span>
    <span class="dot r31d25 water"></span>
    <span class="dot r31d26 water"></span>
    <span class="dot r31d27 water"></span>
    <span class="dot r31d28 water"></span>
    <span class="dot r31d29 water"></span>
    <span class="dot r31d30 water"></span>
    <span class="dot r31d31 water"></span>
    <span class="dot r31d32 water"></span>
    <span class="dot r31d33 water"></span>
    <span class="dot r31d34 water"></span>
    <span class="dot r31d35 water"></span>
    <span class="dot r31d36 africa flicker"></span>
    <span class="dot r31d37 africa flicker"></span>
    <span class="dot r31d38 africa flicker"></span>
    <span class="dot r31d39 water"></span>
    <span class="dot r31d40 water"></span>
    <span class="dot r31d41 water"></span>
    <span class="dot r31d42 water"></span>
    <span class="dot r31d43 water"></span>
    <span class="dot r31d44 water"></span>
    <span class="dot r31d45 water"></span>
    <span class="dot r31d46 water"></span>
    <span class="dot r31d47 water"></span>
    <span class="dot r31d48 water"></span>
    <span class="dot r31d49 water"></span>
    <span class="dot r31d50 water"></span>
    <span class="dot r31d51 water"></span>
    <span class="dot r31d52 water"></span>
    <span class="dot r31d53 water"></span>
    <span class="dot r31d54 australia"></span>
    <span class="dot r31d55 australia"></span>
    <span class="dot r31d56 australia"></span>
    <span class="dot r31d57 australia"></span>
    <span class="dot r31d58 australia"></span>
    <span class="dot r31d59 australia"></span>
    <span class="dot r31d60 australia"></span>
    <span class="dot r31d61 australia"></span>
    <span class="dot r31d62 water"></span>
    <span class="dot r31d63 water"></span>
    <span class="dot r31d64 water"></span>
    <span class="dot r31d65 water"></span>
    <span class="dot r31d66 water"></span>
    <span class="dot r31d67 water"></span>
    <span class="dot r31d68 water"></span>
  </div>
  <div class="maprow r32">
    <span class="dot r32d1 water"></span>
    <span class="dot r32d2 water"></span>
    <span class="dot r32d3 water"></span>
    <span class="dot r32d4 water"></span>
    <span class="dot r32d5 water"></span>
    <span class="dot r32d6 water"></span>
    <span class="dot r32d7 water"></span>
    <span class="dot r32d8 water"></span>
    <span class="dot r32d9 water"></span>
    <span class="dot r32d10 water"></span>
    <span class="dot r32d11 water"></span>
    <span class="dot r32d12 water"></span>
    <span class="dot r32d13 water"></span>
    <span class="dot r32d14 water"></span>
    <span class="dot r32d15 water"></span>
    <span class="dot r32d16 water"></span>
    <span class="dot r32d17 water"></span>
    <span class="dot r32d18 water"></span>
    <span class="dot r32d19 south-america"></span>
    <span class="dot r32d20 south-america"></span>
    <span class="dot r32d21 south-america"></span>
    <span class="dot r32d22 south-america"></span>
    <span class="dot r32d23 water"></span>
    <span class="dot r32d24 water"></span>
    <span class="dot r32d25 water"></span>
    <span class="dot r32d26 water"></span>
    <span class="dot r32d27 water"></span>
    <span class="dot r32d28 water"></span>
    <span class="dot r32d29 water"></span>
    <span class="dot r32d30 water"></span>
    <span class="dot r32d31 water"></span>
    <span class="dot r32d32 water"></span>
    <span class="dot r32d33 water"></span>
    <span class="dot r32d34 water"></span>
    <span class="dot r32d35 water"></span>
    <span class="dot r32d36 africa flicker"></span>
    <span class="dot r32d37 africa flicker"></span>
    <span class="dot r32d38 water"></span>
    <span class="dot r32d39 water"></span>
    <span class="dot r32d40 water"></span>
    <span class="dot r32d41 water"></span>
    <span class="dot r32d42 water"></span>
    <span class="dot r32d43 water"></span>
    <span class="dot r32d44 water"></span>
    <span class="dot r32d45 water"></span>
    <span class="dot r32d46 water"></span>
    <span class="dot r32d47 water"></span>
    <span class="dot r32d48 water"></span>
    <span class="dot r32d49 water"></span>
    <span class="dot r32d50 water"></span>
    <span class="dot r32d51 water"></span>
    <span class="dot r32d52 water"></span>
    <span class="dot r32d53 water"></span>
    <span class="dot r32d54 australia"></span>
    <span class="dot r32d55 australia"></span>
    <span class="dot r32d56 australia"></span>
    <span class="dot r32d57 australia"></span>
    <span class="dot r32d58 australia"></span>
    <span class="dot r32d59 australia"></span>
    <span class="dot r32d60 australia"></span>
    <span class="dot r32d61 australia"></span>
    <span class="dot r32d62 water"></span>
    <span class="dot r32d63 water"></span>
    <span class="dot r32d64 water"></span>
    <span class="dot r32d65 water"></span>
    <span class="dot r32d66 water"></span>
    <span class="dot r32d67 water"></span>
    <span class="dot r32d68 water"></span>
  </div>
</div>
      {<Text />}

</div>
    );
};

export default Map;